import legacyRedirects from './lib/legacy-redirects.json' with { type: 'json' }

/**
 * Drop 123 — preserve link equity from the legacy Frappe site at the apex.
 *
 * The pre-cutover apex (egyptglobe.com) is served by Frappe Cloud and
 * publishes a 267-URL sitemap.xml. The new Next.js build uses a different
 * URL schema. Without redirects, ~60% of GSC-indexed URLs would 404 on
 * cutover — destroying years of accumulated organic equity.
 *
 * lib/legacy-redirects.json holds 236 hand-tuned 301 rules generated by
 * scripts/build-legacy-redirects.mjs (diff legacy paths vs new paths +
 * apply rename rules: agro-products → products/agro, /chemicals →
 * /products/chemicals, /salt → /products/salt, etc.). Cutover-ready —
 * see DROP-123-CUTOVER.md for the runbook.
 */

/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'ohobjnbsybdxntaewqdi.supabase.co' },
      { protocol: 'https', hostname: 'picsum.photos' },
      { protocol: 'https', hostname: 'images.unsplash.com' },
    ],
  },
  async redirects() {
    return legacyRedirects
  },
}
export default nextConfig
